package BankManagement;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class AddAccountMenu extends javax.swing.JDialog {

    private Bank bank;
    private Customer customer;
    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal,Bank bank) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
       this.bank=bank;
     
    }

    AddAccountMenu(MainMenu aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNameLable = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameLable = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        ssnLable = new javax.swing.JLabel();
        ssnField = new javax.swing.JTextField();
        depositeLable = new javax.swing.JLabel();
        depositeField = new javax.swing.JTextField();
        typeLable = new javax.swing.JLabel();
        typeField = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account Menu");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        FirstNameLable.setText("First Name");
        getContentPane().add(FirstNameLable);
        getContentPane().add(FirstNameField);

        LastNameLable.setText("Last Name");
        getContentPane().add(LastNameLable);
        getContentPane().add(LastNameField);

        ssnLable.setText("ID Number:");
        getContentPane().add(ssnLable);
        getContentPane().add(ssnField);

        depositeLable.setText("Initial Deposit ");
        getContentPane().add(depositeLable);
        getContentPane().add(depositeField);

        typeLable.setText("Account Type");
        getContentPane().add(typeLable);

        typeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "checking", "savings" }));
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(typeField);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    StringBuilder warnings = new StringBuilder ();
    String FirstName="",LastName="",ssn="",depositeString="";
    double amount=0;
      if(FirstNameField.getText().isEmpty())
      {
       warnings.append("First name must not be empty\n");
      }
      else{
      FirstName=FirstNameField.getText();
      }
     if(LastNameField.getText().isEmpty())
     {
       warnings.append("Last name must not be empty\n");
     }
     else
     {
        LastName=LastNameField.getText();
     }
     
      if(ssnField.getText().isEmpty()){
       warnings.append("ID number must Not be empty \n");       
    }//GEN-LAST:event_okButtonActionPerformed
      else
      {
      ssn=ssnField.getText();
      }
     if(depositeField.getText().isEmpty())
     {
     warnings.append("Initial deposite must be entered");
     }
     else{
     try
     {
        amount=Double.parseDouble(depositeField.getText());
     }
     catch(NumberFormatException EX)
     {
            warnings.append("Initial deposite must be a number\n"); 
     }
     } 
      
      if(warnings.length()>0)
      {
    JOptionPane.showMessageDialog(this, warnings.toString(),"Input Wornings",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
      Account account =null;
     if(typeField.getSelectedItem().toString()=="checking")
     {
         if(amount>=100)
         {
         account=new Checking(amount);
         }
         else{warnings.append("initial deposite must be atleast 100");}
     }
     
     else if(typeField.getSelectedItem().toString()=="savings")
     {
         if(amount>=50)
         {
         account=new Savings(amount);
         }
         else{warnings.append("initial deposite must be atleast 50");}
     }
   if(account!=null){ 
       
  customer = new Customer(FirstName, LastName, ssn, account);
   bank.addCustomer(customer);
   this.dispose();
      }
   else{ JOptionPane.showMessageDialog(this, warnings.toString(),"Input Wornings",JOptionPane.WARNING_MESSAGE);}
    }
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLable;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField depositeField;
    private javax.swing.JLabel depositeLable;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField ssnField;
    private javax.swing.JLabel ssnLable;
    private javax.swing.JComboBox<String> typeField;
    private javax.swing.JLabel typeLable;
    // End of variables declaration//GEN-END:variables

    Customer getCustomer() {
     return customer;
    }
}
