package BankManagement;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class DepositeMenu extends javax.swing.JDialog {

    private final Customer customer;

    /**
     * Creates new form DepositeMenu
     */
    public DepositeMenu(java.awt.Frame parent, boolean modal,Customer customer) {
	super(parent, modal);
	initComponents();
	setLocationRelativeTo(parent);
	this.customer = customer;
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Amountbtn = new javax.swing.JLabel();
        AmountField = new javax.swing.JTextField();
        Depositebtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Diposit Menu");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        Amountbtn.setText("Deposite Amount:");
        getContentPane().add(Amountbtn);
        getContentPane().add(AmountField);

        Depositebtn.setText("Deposite");
        Depositebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Depositebtn);

        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelbtn);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void DepositebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositebtnActionPerformed
       StringBuilder warnings= new StringBuilder();
       if(AmountField.getText().isEmpty())
       {
       warnings.append("Deposit amount is Reqired");
       }
       else
       {
        double amount =0; 
        try
	{
	 amount=Double.parseDouble( AmountField.getText());
	 int result =JOptionPane.showConfirmDialog(this,"Diposite "+amount+"Rs"+" to the account?\nInterest Earned %:"+(customer.getAccount().getInterset() ));
	 if(result==JOptionPane.OK_OPTION){
	     
	     try {
		 customer.getAccount().deposite(amount);
	         this.dispose();
	     } catch (InvaliedAmountException ex) {
		warnings.append("Invalied Amount\n");
	     }
	 }
	}
         catch(NumberFormatException ex)
	 {
	     warnings.append("Deposite must be a Number\n");
	 }
	
	
	
       }
       
       if(warnings.length()>0)
       {
       JOptionPane.showMessageDialog(this, warnings.toString(),"Deposite Warnings",JOptionPane.WARNING_MESSAGE);
       }       
       
    }//GEN-LAST:event_DepositebtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountField;
    private javax.swing.JLabel Amountbtn;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton Depositebtn;
    // End of variables declaration//GEN-END:variables
}
